# Generated by Django 5.2.4 on 2025-07-24 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=5)),
                ('profile_pic', models.FileField(default='', upload_to='', verbose_name='upload to user_pic/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
