# Generated by Django 5.2.4 on 2025-07-26 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=40)),
                ('charges', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=5)),
                ('sports_pic', models.FileField(default='', upload_to='', verbose_name='upload to SportsCourse_pic/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
