# Generated by Django 5.2.4 on 2025-08-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0004_sportscourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='querry',
            new_name='query',
        ),
    ]
