# Generated by Django 5.2.4 on 2025-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0005_rename_querry_contact_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscourse',
            name='sports_pic',
            field=models.FileField(default='', upload_to='SportsCourse_pic/'),
        ),
    ]
