# Generated by Django 5.2.4 on 2025-08-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0006_alter_sportscourse_sports_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='', upload_to='user_pic/'),
        ),
    ]
