# Generated by Django 5.2.4 on 2025-08-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0007_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscourse',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
