# Generated by Django 5.2.4 on 2025-08-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0008_alter_sportscourse_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscourse',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
