# Generated by Django 5.2.4 on 2025-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0011_admissionform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='full_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
